@startuml
'https://plantuml.com/activity-diagram-beta

start
:Initialize World;
:Start Game Loop;
repeat
if (Mouse being clicked) then (True)
    :Execute current action;
else (False)
endif
if (Game paused) then (False)
    :Update all particles;
else (True)
endif
:Render Current State;



@enduml
